### ISSUE TITLE
IntelliJ IDEA 2022.1 (Ultimate Edition) 无法使用

### ISSUE THREAD

**Issue by Cpanmac** [XmirrorSecurity/OpenSCA-intellij-plugin#2]
Not compatible with the version of your running IDE (IntelliJ IDEA 2022.1)

**Comment by gclm** [comment]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/27618687/175776493-5ddd3e2c-55a1-4db2-9d17-479d24fa4897.png">

**Comment by xxcka** [comment]
1.0.2版本已修复此问题
